apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
spec:
  template:
    spec:
      containers:
        - name: {{ template "fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ template "fullname" . }}
      restartPolicy: Never
  backoffLimit: 4