apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
{{ range $valueName, $value := .Values.config }}
  {{ $valueName }}: {{ $value }}
{{- end}}