apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  ENVIRONMENT_VARIABLE_A: {{ .Values.config.envA }}
  ENVIRONMENT_VARIABLE_B: {{ .Values.config.envB }}
